---
- hosts: ansible
  tasks:
  - name: Build Docker Image using Dockerfile
    command: docker build . -t 243684792514.dkr.ecr.ap-south-1.amazonaws.com/myapp:DOCKER_TAG
    args:
      chdir: /opt/Docker/workspace/Deploy_To_Kubernetes_Using_Ansible_Pipeline_Project
  - name: Docker Authentication
    command: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 243684792514.dkr.ecr.ap-south-1.amazonaws.com
  - name: Push Build Image to AWS ECR Private Repo
    command: docker push 243684792514.dkr.ecr.ap-south-1.amazonaws.com/myapp:DOCKER_TAG
