apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    labels:
        app: myapp
spec:
    replicas: 3
    selector:
        matchLabels:
            app: myapp
    template:
        metadata:
            labels:
                app: myapp
        spec:
            imagePullSecrets:
            - name: docker-private-repo-secret
            containers:
            - name: myapp-container
              image: 243684792514.dkr.ecr.ap-south-1.amazonaws.com/myapp:DOCKER_TAG
              imagePullPolicy: Always
              ports:
              - containerPort: 8080

    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
    name: myapp-service
    labels:
        app: myapp
spec:
    selector:
        app: myapp
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
    type: LoadBalancer
